### ISSUE TITLE
Training and Testing

### ISSUE THREAD

**Issue by sertankaya** [Zheng222/IMDN#11]
Hi Zheng,

This a great repo. Appreciate for letting us use it. I have 2 questions regarding training and testing.

1-) Why do we use testing data (testing folders) as validation data during training ?
In train_IMDN.py:
![image](https://user-images.githubusercontent.com/16074792/76589958-156df600-64a9-11ea-9658-86691a697afe.png)

2-) Can we test our LR images without corresponding HR images? Ideally, we want to generate HR images from LR images? Do we have to have --test_hr_folder in order to test LR images?

python test_IMDN.py --test_hr_folder Test_Datasets/Set5/ --test_lr_folder Test_Datasets/Set5_LR/x2/ --output_folder results/Set5/x2 --checkpoint checkpoints/IMDN_x2.pth --upscale_factor 2

**Comment by Zheng222** [comment]
@sertankaya 
Hello, 1. Through Set5 dataset is testing data, it is usually used in the valid phase in the SR field.

2. The `--test_hr_folder` is for computing PSNR and SSIM, so you can modify the test_IMDN.py to implement your goal.
