### ISSUE TITLE
EDSR's forward_chop replace the crop_forward

### ISSUE THREAD

**Issue by zrongcheng** [Zheng222/IMDN#13]
Thanks for your excellent works. 
I have a question. I tested my images(3040x3040 or 6080x3040) with EDSR, little change in gpu memory . but, when i tested your IMDN with forward_chop, why the memory change so much?

**Comment by Zheng222** [comment]
@zrongcheng Hello, the basic block of EDSR is different from IMDN, which has nothing to do with crop strategy. You can calculate the Line Buffer of basic blocks of EDSR and IMDN.
