### ISSUE TITLE
test time

### ISSUE THREAD

**Issue by Lininggggggg** [Zheng222/IMDN#17]
hello, i have a issue about test time.
i test the code with the Set5 by i5 cpu, but i get the time is about 4.4s;
and i know the cpu time will big but i think this time is too big, right?
because the flops is smaller than fsrcnn and almost models, and the gpu time is the same as others, even though the depth is different.

the reason is the depth?? if really it is, why the gpu time is still small?

**Comment by Zheng222** [comment]
@Lininggggggg How do you test the inference time on CPU? Which time record time do you use? Are you use warm-up?

**Comment by Lininggggggg** [comment]
i test it with scale is 4, the input size is 180*320, the number of pics is about 20.
and i test the time is just the model rather than including the loading time.
i use time record function is timer().
and could you tell me about your inference time on CPU?

**Comment by Lininggggggg** [comment]
> @Lininggggggg How do you test the inference time on CPU? Which time record function do you use? Do you use warm-up?

i test it with scale is 4, the input size is 180*320, the number of pics is about 20.
and i test the time is just the model rather than including the loading time.
i use time record function is timer().
and could you tell me about your inference time on CPU?

**Comment by Zheng222** [comment]
@Lininggggggg I test the model only on GPU. You can try print inference time of each image to ensure the first record time is normal.
