### ISSUE TITLE
PSNR

### ISSUE THREAD

**Issue by lightfate** [Zheng222/IMDN#23]
wheather is the psnr in these pictures based on y-channel or RGB-channel?
![image](https://user-images.githubusercontent.com/41222646/97657428-c7901780-1aa4-11eb-8f79-c1f7479ad18f.png)
![image](https://user-images.githubusercontent.com/41222646/97657435-cbbc3500-1aa4-11eb-8567-1fe0a23e480a.png)

**Comment by fantasysponge** [comment]
> wheather is the psnr in these pictures based on y-channel or RGB-channel?
> ![image](https://user-images.githubusercontent.com/41222646/97657428-c7901780-1aa4-11eb-8f79-c1f7479ad18f.png)
> ![image](https://user-images.githubusercontent.com/41222646/97657435-cbbc3500-1aa4-11eb-8567-1fe0a23e480a.png)

In paper 4.1 , we calculate the values on the luminance channel

**Comment by lightfate** [comment]
thank you~
