### ISSUE TITLE
checkpoint下的是训练完的模型吗？

### ISSUE THREAD

**Issue by Lininggggggg** [Zheng222/IMDN#24]
请问为什么我直接加载您在文件夹checkpoint下的模型进行测试，结果只有8db，是因为你放的是仅初始化的模型吗？

**Comment by Zheng222** [comment]
@Lininggggggg checkpoint 下是训练好的模型，结果的话我这边测试是准确的。同样的，你也可以参考张凯博士的[KAIR](https://github.com/cszn/KAIR)，里面也有IMDN的训练及测试代码。

**Comment by Lininggggggg** [comment]
好的，感谢
