### ISSUE TITLE
about train dataset DIV2K

### ISSUE THREAD

**Issue by SuperPengXue** [Zheng222/IMDN#25]
Thanks for release amazing work
Is  ‘Training dataset DIV2K’   same with 'Train Data (HR images)' in https://data.vision.ee.ethz.ch/cvl/DIV2K/??
Can you provide the baidunetdisk of ‘Training dataset DIV2K’，thanks

**Comment by Zheng222** [comment]
@SuperPengXue 
Yes, it is. I'm sorry I don't upload the DIV2K training dataset to "百度网盘". I have a google drive link to the DIV2K dataset. 

[DIV2K](https://drive.google.com/file/d/12hOYsMa8t1ErKj6PZA352icsx9mz1TwB/view?usp=sharing)
