### ISSUE TITLE
IMDN_AS任意比例

### ISSUE THREAD

**Issue by djdll** [Zheng222/IMDN#31]
您好当我使用IMDN_AS时，一旦改变upscale就会报错，是不可以更改这个参数吗？size mismatch for upsampler.0.weight: copying a param with shape torch.Size([48, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([12, 64, 3, 3]).
	size mismatch for upsampler.0.bias: copying a param with shape torch.Size([48]) from checkpoint,

**Comment by Zheng222** [comment]
@djdll 这里没有提供训练IMDN_AS的代码，训练IMDN_AS需要加载`data/RealSR.py`且不需要upscale参数。直接测试IMDN_AS的话请使用`test_IMDN_AS.py`

**Comment by djdll** [comment]
好的谢谢您，因为您提供的方法分辨率并未改变（lr->hr）所以是训练的时候并没有设置更大的倍数是嘛，例如我想方大5倍是不能实现的是嘛

**Comment by djdll** [comment]
好的谢谢您，因为您提供的方法分辨率并未改变（lr->hr）所以是训练的时候并没有设置更大的倍数是嘛，例如我想方大5倍是不能实现的是嘛

**Comment by Zheng222** [comment]
> 好的谢谢您，因为您提供的方法分辨率并未改变（lr->hr）所以是训练的时候并没有设置更大的倍数是嘛，例如我想方大5倍是不能实现的是嘛

放大5倍的话可以先用双三次插值将LR图像放大5倍，然后用IMDN_AS模型就可以了。
