### ISSUE TITLE
about train and checkpoint 

### ISSUE THREAD

**Issue by zymize** [Zheng222/IMDN#6]
hello,nice to meet you
I want to ask that 
is checkpoint a pre-train model?
and how can i train it? thanks
looking forward your reply

**Comment by zymize** [comment]
what's more,I found my testing time has a problem as following:

Namespace(checkpoint='checkpoints/IMDN_x2.pth', cuda=True, is_y=True, output_folder='results/Set5/x2', test_hr_folder='Test_Datasets/Set5/', test_lr_folder='Test_Datasets/Set5_LR/x2/', upscale_factor=2)
Mean PSNR: 37.91055018265467, SSIM: 0.9594468667890528, TIME: 954.8178810119629 ms

**Comment by Zheng222** [comment]
@zymize Please check out your device. https://github.com/Zheng222/IMDN/blob/0dd1c373e7ecb2d518acc049f5640ac554cd3714/test_IMDN.py#L30
We test the inference snippet on `Nvidia TITAN Xp.`
About the training time, you can also refer to #4.

**Comment by zymize** [comment]
thank you for your kind reply. 
what's more,I have another question about your IDN work. I couldn't send 800 photos to train this work beause I just have 16G CPU.
Could I send 800 photos dividing two parts? 
How to achieve  it?
looking forword to your reply. thank you verch again.

**Comment by Zheng222** [comment]
@zymize you can rewrite the pytorch code for IDN, 16G RAM is enough for training IDN.

**Comment by zymize** [comment]
Thanks for your reply. I resolve this question for adding CPU.
  But someone use your caffe code  IDN's X2 PSNR result of the paper  in compared table is 37.75 .
  And I use tensorflow code, the same is 37.75. When I compare your IDN's work, ,can I write that the IDN's X2 PSNR result of the paper is 37.75 ? If my result is higher 37.75 the same environment, can I think that my work is effective?

**Comment by Zheng222** [comment]
@zymize Hello, I have listed the result in [IDN-tensorflow](https://github.com/Zheng222/IDN-tensorflow). You can directly copy these results. For fair comparison, you should use the [matlab evaluation code](https://github.com/yulunzhang/RCAN/blob/master/RCAN_TestCode/Evaluate_PSNR_SSIM.m) to test PSNR, not use python skimage.measure.compute_psnr(). Thank you!

**Comment by zymize** [comment]
@Zheng222 OK thanks for  your reminding. I am sorry to forget to test your code on Matlab.
I use your original code to test on Matlab . I cannot acheive your results by my training . Could you give  me  some suggestions to get your results?

**Comment by Zheng222** [comment]
Hello, I recommend that you train a few more epochs at learning rates of 2e-4 and 1e-4.
