### ISSUE TITLE
About parameters

### ISSUE THREAD

**Issue by UESTCshiny** [Zheng222/IMDN#8]
Hello! I want to ask how you caculate the parameters of IDN? I use torchsummaryX to caculate the model size, but the parameters is about 677k.

**Comment by Zheng222** [comment]
@UESTCshiny  Hello, you can calculate the parameters of IDN manually through Eq. 9 in IMDN. Please note that the input channel of IDN is 1, and the output channel is also 1. I recommend that you use [thop](https://github.com/Lyken17/pytorch-OpCounter) in PyTorch to calculate model parameters and FLOPs.
