### ISSUE TITLE
Adaptive Cropping Strategy

### ISSUE THREAD

**Issue by sureJ0824** [Zheng222/IMDN#9]
你好，首先非常感谢您的开源工作，在阅读文章的时候对于其中的adaptive cropping strategy的内容理解的还不够透彻，想请问一下，ACS的具体作用是什么呢，使用ACS之后为什么就可以处理arbitrary size和any scale factor 了呢，如果有时间希望您可以帮忙解惑一下，感谢

**Comment by Zheng222** [comment]
@sureJ0824 
To solve the super-resolution of arbitrary scale factor with a single model, the first step is upscaling the original small size low-resolution image to the target size. Assuming an input size is 640×480 and a target is 960×720 (1280×960), the upscale factor is 1.5 (2). Employing ACS, an image of arbitrary size can be cropped to 4 patches that can be divisible by 4. Then they are fed into IMDN_AS (Figure 5) to get the final super-resolved result.

For example, to process “cam1_08.png” with a size of 2801×2001 in RealSR valuation dataset, EDSR-baseline must crop the image to 2800×2000 (2799×2001), down-sample it to 700×500 (933×667) and then put it into the model at a scale factor of 4 (3). This model only produces 2800×2000 (2799×2001) image. Thus, this approach cannot treat this image. With ACS, our model can directly output 2801×2001 image.

**Comment by sureJ0824** [comment]
Thank you for your detailed explanation. I understand it, it means when we solve arbitrary scale factor or arbitrary size, we default that the LR image is the same size with the HR size.
Thank you sincerely




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zheng Hui (惠政)"<notifications@github.com&gt;; 
发送时间: 2020年2月22日(星期六) 晚上9:14
收件人: "Zheng222/IMDN"<IMDN@noreply.github.com&gt;; 
抄送: "1226510143"<1226510143@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Zheng222/IMDN] Adaptive Cropping Strategy (#9)




@sureJ0824
 To solve the super-resolution of arbitrary scale factor with a single model, the first step is upscaling the original small size low-resolution image to the target size. Assuming an input size is 640×480 and a target is 960×720 (1280×960), the upscale factor is 1.5 (2). Employing ACS, an image of arbitrary size can be cropped to 4 patches that can be divisible by 4. Then they are fed into IMDN_AS (Figure 5) to get the final super-resolved result.
 
For example, to process “cam1_08.png” with a size of 2801×2001 in RealSR valuation dataset, EDSR-baseline must crop the image to 2800×2000 (2799×2001), down-sample it to 700×500 (933×667) and then put it into the model at a scale factor of 4 (3). This model only produces 2800×2000 (2799×2001) image. Thus, this approach cannot treat this image. With ACS, our model can directly output 2801×2001 image.

**Comment by nan-rock** [comment]
thanks for the wonderful concept.
can u please let me know exactly where in the code is this strategy of adaptive cropping
